/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import "../i18n";
import { StyleSheet, View } from "react-native";
import { useCallback, useEffect } from "react";
// Initialize Matter adapter early
import "@native-adaptors/implementations/ESPMatterAdapter";
// hooks
import { useCDF } from "@shared/hooks/useCDF";
import { useRouter, usePathname, useFocusEffect } from "expo-router";
// components
import { Logo } from "@shared/components";
import { registerForNotification } from "@shared/utils/notifications";
import { executePostLoginPipeline, navigateToHomeAfterAuth } from "@features/auth/utils/postLoginPipeline";
import { isConsentAccepted } from "@features/consent";
import { getFeatures } from "@config/features.config";
import { isCnRegion } from "@config/region.config";
import { getPreAuthRoute } from "@features/landing";
// theme
import { tokens } from "@shared/theme/tokens";

/**
 * Root splash / auth gate: runs post-login pipeline or redirects to login.
 */
const Index = () => {
  const router = useRouter();
  const pathname = usePathname();
  const { store, isInitialized, syncHomeWithNodes, initUserCustomData } =
    useCDF();

  const user = store?.userStore.user;

  const authCheck = async () => {
    try {
      // CN region: gate the entire startup flow behind privacy consent.
      // Until accepted, redirect to the consent screen (which also unlocks the
      // deferred native permission prompts on agree).
      if (isCnRegion() && !(await isConsentAccepted())) {
        if (!pathname.includes("/Consent")) {
          // Cast: typed routes are regenerated by expo prebuild/start; matches
          // the existing pattern used for other dynamically-gated routes.
          router.replace("/(consent)/Consent" as never);
        }
        return
      }

      if (user) {
        // Session restored: enter Home first, hydrate in the background.
        navigateToHomeAfterAuth(router);
        void executePostLoginPipeline({
          store,
          syncHomeWithNodes,
          initUserCustomData,
        }).catch((error: unknown) => {
          console.warn("[Index] post-login pipeline failed:", error);
        });
        return;
      }

      const validRoutes = [
        "/Landing",
        "/ConfirmationCode",
        "/Forgot",
        "/Login",
        "/Signup",
      ];
      const isAuthRoute = validRoutes.some((route) => pathname.includes(route));
      if (!isAuthRoute) {
        router.replace(getPreAuthRoute() as never);
      }
    } catch {
      await user?.logout();
      router.replace(getPreAuthRoute() as never);
    }
  };

  useFocusEffect(
    useCallback(() => {
      if (!store || !isInitialized) {
        return;
      }
      void authCheck();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- intentional hook deps
    }, [store, isInitialized]),
  );

  // Initialize notification when user is logged in. Skipped when the
  // notifications feature is disabled (e.g. CN builds, which ship without
  // Firebase/FCM), so we never attempt to fetch an FCM token there.
  useEffect(() => {
    if (user && isInitialized && getFeatures().notifications) {
      initNotification();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps -- intentional hook deps
  }, [user, isInitialized]);

  const initNotification = async () => {
    try {
      await registerForNotification(store);
    } catch (err) {
      console.error(err);
      console.error("Failed to initialize notification");
    }
  };

  return (
    <View style={styles.splashScreen}>
      <Logo qaId="logo_index" />
    </View>
  );
};

export default Index;

const styles = StyleSheet.create({
  splashScreen: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: tokens.colors.white,
  },
});
