/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Config-layer barrel for Matter cluster / device-type tokens.
 * Source of truth lives in `ESPRMMatterBase/constants.ts`; re-exported here so
 * `config/*` and `src/shared` can consume Matter mappings without importing
 * `src/sdk-adaptors` directly.
 */
export {
  ESPRMMatterBaseAdaptorIdentifier,
  MATTER_CLUSTER_ID_COLOR_CONTROL,
  MATTER_CLUSTER_ID_DOOR_LOCK,
  MATTER_CLUSTER_ID_ILLUMINANCE_MEASUREMENT,
  MATTER_CLUSTER_ID_LEVEL_CONTROL,
  MATTER_CLUSTER_ID_OCCUPANCY_SENSING,
  MATTER_CLUSTER_ID_ON_OFF,
  MATTER_CLUSTER_ID_POWER_SOURCE,
  MATTER_CLUSTER_ID_RELATIVE_HUMIDITY_MEASUREMENT,
  MATTER_CLUSTER_ID_RVC_CLEAN_MODE,
  MATTER_CLUSTER_ID_RVC_OPERATIONAL_STATE,
  MATTER_CLUSTER_ID_RVC_RUN_MODE,
  MATTER_CLUSTER_ID_TEMPERATURE_MEASUREMENT,
  MATTER_DEVICE_TYPE_DOOR_LOCK,
  MATTER_DEVICE_TYPE_EXTENDED_COLOR_LIGHT,
  MATTER_DEVICE_TYPE_GENERIC_SENSOR,
  MATTER_DEVICE_TYPE_HUMIDITY_SENSOR,
  MATTER_DEVICE_TYPE_ID_DOOR_LOCK,
  MATTER_DEVICE_TYPE_ID_EXTENDED_COLOR_LIGHT,
  MATTER_DEVICE_TYPE_ID_GENERIC_SENSOR,
  MATTER_DEVICE_TYPE_ID_HUMIDITY_SENSOR,
  MATTER_DEVICE_TYPE_ID_ILLUMINANCE_SENSOR,
  MATTER_DEVICE_TYPE_ID_OCCUPANCY_SENSOR,
  MATTER_DEVICE_TYPE_ID_RVC,
  MATTER_DEVICE_TYPE_ID_TEMPERATURE_SENSOR,
  MATTER_DEVICE_TYPE_ILLUMINANCE_SENSOR,
  MATTER_DEVICE_TYPE_OCCUPANCY_SENSOR,
  MATTER_DEVICE_TYPE_PREFIX,
  MATTER_DEVICE_TYPE_RVC,
  MATTER_DEVICE_TYPE_TEMPERATURE_SENSOR,
  MATTER_NEEDS_FABRIC_CONVERSION,
  MATTER_SERVER_PARAM_TYPE_COLOR_CONTROL,
  MATTER_SERVER_PARAM_TYPE_DOOR_LOCK,
  MATTER_SERVER_PARAM_TYPE_LEVEL_CONTROL,
  MATTER_SERVER_PARAM_TYPE_ON_OFF,
  MATTER_SERVER_PARAM_TYPE_POWER_SOURCE,
  MATTER_SERVER_PARAM_TYPE_PREFIX,
  MATTER_SERVER_PARAM_TYPE_RVC_CLEAN_MODE,
  MATTER_SERVER_PARAM_TYPE_RVC_RUN_MODE,
  toMatterDeviceType,
  toMatterServerParamType,
} from "@sdk-adaptors/ESPRMMatterBase/constants";
